OPENAI_API_KEY = "sk-proj-rcxHwF9xe6wBQ2XHPBW3T3BlbkFJrxv6vmMvkxgNPZf8gA3r"
OPENAI_MODEL = "gpt-4o-mini"

NEO4J_URI = "neo4j+s://d0274097.databases.neo4j.io"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "F3TI3TQ5dx9a2DIBQPlcYxdGKYRG560WXxZYncH3Wg8"