OPENAI_API_KEY = "sk-proj-rcxHwF9xe6wBQ2XHPBW3T3BlbkFJrxv6vmMvkxgNPZf8gA3r"
OPENAI_MODEL = "gpt-4o-mini"

NEO4J_URI = "bolt://54.173.143.143:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "children-cent-rack"